// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuVwWNEysOrIHSldyjzrm8TlAFKqQZv-o',
    appId: '1:937240764574:web:dfab2c56aaf183db92db8f',
    messagingSenderId: '937240764574',
    projectId: 'asbin-5d7df',
    authDomain: 'asbin-5d7df.firebaseapp.com',
    databaseURL: 'https://asbin-5d7df-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'asbin-5d7df.appspot.com',
    measurementId: 'G-XZHFKJS1LC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1oFAI_rjpv0-N2dNgxNLRPgjoi3u11NI',
    appId: '1:937240764574:android:6580c9898b6380db92db8f',
    messagingSenderId: '937240764574',
    projectId: 'asbin-5d7df',
    databaseURL: 'https://asbin-5d7df-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'asbin-5d7df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu62LKy0pD1ses3Cb5NRAyWgkwFy62E9U',
    appId: '1:937240764574:ios:315880f3667eec7a92db8f',
    messagingSenderId: '937240764574',
    projectId: 'asbin-5d7df',
    databaseURL: 'https://asbin-5d7df-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'asbin-5d7df.appspot.com',
    iosClientId: '937240764574-q2181o25bud5h7ek1mn4pqunjqbr4t23.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectAsbin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu62LKy0pD1ses3Cb5NRAyWgkwFy62E9U',
    appId: '1:937240764574:ios:315880f3667eec7a92db8f',
    messagingSenderId: '937240764574',
    projectId: 'asbin-5d7df',
    databaseURL: 'https://asbin-5d7df-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'asbin-5d7df.appspot.com',
    iosClientId: '937240764574-q2181o25bud5h7ek1mn4pqunjqbr4t23.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectAsbin',
  );
}
